### ISSUE TITLE
doesn't work?

### ISSUE THREAD

**Issue by devwheel** [microsoft/powerbi-visuals-mekkochart#45]
I've downloaded, run npm i, pbiviz start and get an error on events.js:183 unhandled 'error' event

**Comment by zBritva** [comment]
Hello, could you check that port 8080 is free. Looks similar to: https://stackoverflow.com/questions/48765445/node-js-error-message-events-js183-throw-er-unhandled-error-event

**Comment by devwheel** [comment]
this morning it made it further but got a bunch of polyfill errors.

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.for-each' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 3:0-55
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 5:0-55
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.queue-microtask' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 7:0-46
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.url' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 9:0-34
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.url-search-params' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 13:0-48
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

ERROR in ./node_modules/@babel/polyfill/lib/noConflict.js
Module not found: Error: Can't resolve 'core-js/modules/web.url.to-json' in 'C:\_SPFX\_PowerBI\mekkochart\node_modules\@babel\polyfill\lib'
 @ ./node_modules/@babel/polyfill/lib/noConflict.js 11:0-42
 @ ./node_modules/@babel/polyfill/lib/index.js
 @ ./src/visual.ts
 @ ./.tmp/precompile/visualPlugin.ts
 @ multi ./.tmp/precompile/visualPlugin.ts

**Comment by zBritva** [comment]
If you use the latest version of tools, it requires corejs 3. you need to replace Babel by core-js package. The visual build by 3.1.0, 3.1.0 uses Babel, not core-js:
https://github.com/microsoft/powerbi-visuals-mekkochart/blob/master/package.json#L64
